// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tour.DDD.Infraestructure;

#nullable disable

namespace tour.DDD.Infraestructure.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tour.DDD.Domain.Generico.BodegaEvento", b =>
                {
                    b.Property<string>("AlmacenadoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AgregadoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlmacenadoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuerpoEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlmacenadoId");

                    b.ToTable("EventosAlmacenados", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
